export const initialSeats = [
    [
      { id: 1, occupied: false, selected: false },
      { id: 2, occupied: false, selected: false },
      { id: 3, occupied: false, selected: false },
      { id: 4, occupied: false, selected: false },
      { id: 5, occupied: false, selected: false },
      { id: 6, occupied: false, selected: false },
      { id: 7, occupied: false, selected: false },
      { id: 8, occupied: false, selected: false },
    ],
    [
      { id: 9, occupied: false, selected: false },
      { id: 10, occupied: false, selected: false },
      { id: 11, occupied: false, selected: false },
      { id: 12, occupied: true, selected: false },
      { id: 13, occupied: true, selected: false },
      { id: 14, occupied: false, selected: false },
      { id: 15, occupied: false, selected: false },
      { id: 16, occupied: false, selected: false },
    ],
    [
      { id: 17, occupied: false, selected: false },
      { id: 18, occupied: false, selected: false },
      { id: 19, occupied: false, selected: false },
      { id: 20, occupied: false, selected: false },
      { id: 21, occupied: false, selected: false },
      { id: 22, occupied: false, selected: false },
      { id: 23, occupied: true, selected: false },
      { id: 24, occupied: true, selected: false },
    ],
    [
      { id: 25, occupied: false, selected: false },
      { id: 26, occupied: false, selected: false },
      { id: 27, occupied: false, selected: false },
      { id: 28, occupied: false, selected: false },
      { id: 29, occupied: false, selected: false },
      { id: 30, occupied: false, selected: false },
      { id: 31, occupied: false, selected: false },
      { id: 32, occupied: false, selected: false },
    ],
    [
      { id: 33, occupied: false, selected: false },
      { id: 34, occupied: false, selected: false },
      { id: 35, occupied: false, selected: false },
      { id: 36, occupied: true, selected: false },
      { id: 37, occupied: true, selected: false },
      { id: 38, occupied: false, selected: false },
      { id: 39, occupied: false, selected: false },
      { id: 40, occupied: false, selected: false },
    ],
    [
      { id: 41, occupied: false, selected: false },
      { id: 42, occupied: false, selected: false },
      { id: 43, occupied: false, selected: false },
      { id: 44, occupied: false, selected: false },
      { id: 45, occupied: true, selected: false },
      { id: 46, occupied: true, selected: false },
      { id: 47, occupied: true, selected: false },
      { id: 48, occupied: false, selected: false },
    ],
  ];